#!/usr/bin/env python3
"""Build the sttbench WER regression corpus (tools/sttbench/corpus/).

The committed corpus is the OUTPUT of this script; re-running it reproduces the
same clips (same source utterances, same seeded noise). It exists so every clip's
provenance is code, not a claim. Sources (see corpus/README.md for licences):

  * LibriSpeech test-clean (CC BY 4.0), fetched per utterance through the Hugging
    Face datasets-server rows API (openslr/librispeech_asr, config clean, split
    test) — no 346 MB tarball needed.
  * EdAcc, the Edinburgh International Accents of English Corpus (CC BY-SA 4.0),
    same API (edinburghcstr/edacc, split test) — the non-native-accent clips.
  * Noise, hum, room tone and silence generated here from a fixed seed.

Every clip is written as 16 kHz mono 16-bit PCM WAV, the capture format the app
feeds Whisper. Run from the repo root inside the sttbench venv:

    python tools/sttbench/build_corpus.py
"""
import io
import json
import time
import urllib.request
from pathlib import Path

import numpy as np
import soundfile as sf

SR = 16000
OUT = Path(__file__).resolve().parent / "corpus"
ROWS = "https://datasets-server.huggingface.co/rows?dataset={ds}&config={cfg}&split={split}&offset={off}&length=1"
LS = ("openslr/librispeech_asr", "clean", "test")
EDACC = ("edinburghcstr/edacc", "default", "test")
RNG = np.random.default_rng(20260929)

LS_LICENSE = "CC BY 4.0 (LibriSpeech test-clean, openslr.org/12)"
EDACC_LICENSE = "CC BY-SA 4.0 (EdAcc, datashare.ed.ac.uk/handle/10283/4836)"
GEN_LICENSE = "generated by build_corpus.py (Apache-2.0, this repo)"


def fetch_row(ds, cfg, split, off):
    """One datasets-server row -> (row dict, float32 mono 16 kHz audio)."""
    url = ROWS.format(ds=ds, cfg=cfg, split=split, off=off)
    for attempt in range(6):
        try:
            d = json.load(urllib.request.urlopen(url, timeout=60))
            row = d["rows"][0]["row"]
            src = row["audio"][0]["src"]
            data = urllib.request.urlopen(src, timeout=120).read()
            x, sr = sf.read(io.BytesIO(data), dtype="float32", always_2d=True)
            return row, resample(x.mean(axis=1), sr)
        except Exception as e:  # rate limits (429) are routine on the public API
            print(f"  retry {ds}#{off}: {e}")
            time.sleep(5 * (attempt + 1))
    raise SystemExit(f"could not fetch {ds} row {off}")


def resample(x, sr):
    if sr == SR:
        return x.astype(np.float32)
    n = int(round(len(x) * SR / sr))
    # FFT resample: exact band-limiting, fine for short clips.
    X = np.fft.rfft(x)
    keep = min(len(X), n // 2 + 1)
    Y = np.zeros(n // 2 + 1, dtype=complex)
    Y[:keep] = X[:keep]
    return (np.fft.irfft(Y, n) * (n / len(x))).astype(np.float32)


def rms(x):
    return float(np.sqrt(np.mean(np.square(x, dtype=np.float64)) + 1e-12))


def mix_at_snr(speech, noise, snr_db):
    noise = noise[: len(speech)]
    gain = rms(speech) / (rms(noise) * 10 ** (snr_db / 20))
    return speech + noise * gain


def pink(n):
    """Pink (1/f) noise via spectral shaping, unit RMS."""
    X = np.fft.rfft(RNG.standard_normal(n))
    f = np.arange(len(X)); f[0] = 1
    y = np.fft.irfft(X / np.sqrt(f), n)
    return (y / rms(y)).astype(np.float32)


def brown(n):
    y = np.cumsum(RNG.standard_normal(n))
    y = y - np.convolve(y, np.ones(1601) / 1601, mode="same")  # remove drift
    return (y / rms(y)).astype(np.float32)


def at_dbfs(x, dbfs):
    return (x / rms(x) * 10 ** (dbfs / 20)).astype(np.float32)


def insert_pause(x, pause_s):
    """Insert a pause at the quietest 20 ms frame in the middle of the clip —
    a word gap, so no word is split (the mid-sentence thinking pause)."""
    hop = SR // 50
    frames = [rms(x[i:i + hop]) for i in range(0, len(x) - hop, hop)]
    lo, hi = int(len(frames) * 0.4), int(len(frames) * 0.6)
    k = lo + int(np.argmin(frames[lo:hi]))
    cut = k * hop + hop // 2
    gap = at_dbfs(RNG.standard_normal(int(pause_s * SR)).astype(np.float32), -70)
    return np.concatenate([x[:cut], gap, x[cut:]]), cut / SR


def write(clip_id, x, meta, manifest):
    x = np.clip(x, -1.0, 1.0)
    peak = float(np.max(np.abs(x)))
    if peak > 0.98:
        x = x * (0.98 / peak)
    sf.write(OUT / f"{clip_id}.wav", x, SR, subtype="PCM_16")
    meta = dict(meta, id=clip_id, seconds=round(len(x) / SR, 2))
    manifest.append(meta)
    print(f"{clip_id:22s} {meta['seconds']:6.2f}s  {meta['category']}")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = []

    def ls(off):
        row, x = fetch_row(*LS, off)
        time.sleep(1.0)
        return row, x

    def ls_meta(row, cat, **kw):
        return dict(category=cat, reference=row["text"], source=f"LibriSpeech test-clean {row['id']}",
                    license=LS_LICENSE, **kw)

    # Short commands/questions (2-4 s), six LibriSpeech speakers.
    for i, off in enumerate([7, 145, 185, 262, 312, 116], 1):
        row, x = ls(off)
        write(f"short_{i:02d}", x, ls_meta(row, "short"), manifest)

    # Long single utterances (> 10 s) — the old early start transcribed only the
    # last 6 s of these.
    for i, off in enumerate([4, 91, 138, 265], 1):
        row, x = ls(off)
        write(f"long_{i:02d}", x, ls_meta(row, "long"), manifest)

    # Very long (> 30 s): past Whisper's 30 s window, exercises windowed decoding.
    row, x = ls(316)
    write("verylong_01", x, ls_meta(row, "verylong"), manifest)

    # A mid-sentence thinking pause (1.4 s of near-silence at a word gap).
    for i, off in enumerate([181, 311], 1):
        row, x = ls(off)
        y, at = insert_pause(x, 1.4)
        write(f"pause_{i:02d}", y, ls_meta(row, "pause", note=f"1.4 s pause inserted at {at:.2f} s"), manifest)

    # Noisy: white 10 dB, pink 5 dB, babble 5 dB (babble = three other speakers).
    row, x = ls(13)
    write("noisy_white10", mix_at_snr(x, RNG.standard_normal(len(x)).astype(np.float32), 10),
          ls_meta(row, "noisy", note="white noise, SNR 10 dB"), manifest)
    row, x = ls(222)
    write("noisy_pink5", mix_at_snr(x, pink(len(x)), 5), ls_meta(row, "noisy", note="pink noise, SNR 5 dB"), manifest)
    row, x = ls(148)
    babble = np.zeros(len(x), np.float32)
    for off in (20, 82, 247):
        _, b = ls(off)
        b = np.resize(b, len(x)); babble += b / rms(b)
    write("noisy_babble5", mix_at_snr(x, babble, 5),
          ls_meta(row, "noisy", note="3-talker babble (LibriSpeech 6930-75918-0020, 1320-122617-0004, 260-123288-0015), SNR 5 dB"),
          manifest)

    # Non-speech only: the hallucination check. The reference is empty — any
    # transcript at all is a hallucination.
    n = 3 * SR
    t = np.arange(4 * SR) / SR
    hum = sum(np.sin(2 * np.pi * 50 * k * t) / k for k in (1, 2, 3, 4)).astype(np.float32)
    clicks = np.zeros(4 * SR, np.float32)
    for c in RNG.integers(0, 4 * SR - 400, 14):
        clicks[c:c + 400] += (RNG.standard_normal(400) * np.exp(-np.arange(400) / 60)).astype(np.float32)
    silence = [
        ("silence_digital", at_dbfs(RNG.standard_normal(n).astype(np.float32), -80), "dithered digital silence, -80 dBFS"),
        ("silence_roomtone", at_dbfs(pink(4 * SR), -50), "pink room tone, -50 dBFS"),
        ("silence_hum", at_dbfs(hum, -30) + at_dbfs(pink(4 * SR), -60), "50 Hz mains hum + harmonics, -30 dBFS"),
        ("silence_fan", at_dbfs(brown(4 * SR), -32), "brown fan/air noise, -32 dBFS"),
        ("silence_clicks", at_dbfs(clicks, -35) + at_dbfs(pink(4 * SR), -60), "keyboard-like clicks, -35 dBFS"),
    ]
    for cid, x, note in silence:
        write(cid, x, dict(category="silence", reference="", source="generated", license=GEN_LICENSE, note=note), manifest)

    # Non-native accents (EdAcc conversational English; L1 recorded per clip).
    for i, off in enumerate([462, 787, 1084, 2638], 1):
        row, x = fetch_row(*EDACC, off)
        time.sleep(1.0)
        write(f"accent_{i:02d}", x, dict(category="accent", reference=row["text"],
                                          source=f"EdAcc test row {off} ({row['speaker']})",
                                          license=EDACC_LICENSE, note=f"L1 {row['l1']}"), manifest)

    with open(OUT / "manifest.jsonl", "w") as f:
        for m in manifest:
            f.write(json.dumps(m, sort_keys=True) + "\n")
    total = sum(p.stat().st_size for p in OUT.glob("*.wav"))
    print(f"{len(manifest)} clips, {total / 1e6:.2f} MB")


if __name__ == "__main__":
    main()
